### ISSUE TITLE
我这边投屏正常，adb devices 正常显示设备，但在输入两个点坐标后，没有触发相应的动作。

### ISSUE THREAD

**Issue by LvrenW** [Nihiue/JumpHelper#1]

**Comment by LvrenW** [comment]
![default](https://user-images.githubusercontent.com/17001359/34440745-3d9eabb4-ecf2-11e7-8720-986737ff1f5d.PNG)
投屏使用的第三方软件——Total Control

**Comment by Nihiue** [comment]
之前写的模拟触摸点的坐标比较靠上，可能点到标题栏了，可以下载新版本试一下

**Comment by LvrenW** [comment]
可能软件没有关系，现在新旧版都可以触发动作了。我之前用的不是powdershell，用的是cmd命令行查看的adb配置，刚刚重新配置了Powershell的adb环境，就可以正常跑了。假期愉快！
