### ISSUE TITLE
可以计算，但无法触发按压屏幕

### ISSUE THREAD

**Issue by catcherxuefeng** [Nihiue/JumpHelper#2]

**Comment by Nihiue** [comment]
可能是ADB配置或者版本有问题，下载新版本， 里面自带 ADB 配置和测试功能

**Comment by catcherxuefeng** [comment]
不是的，我已经用那个AI的了，那个可以正常使用，谢谢

2017-12-30 12:29 GMT+08:00 WangLei <notifications@github.com>:
